-- 코드를 입력하세요
WITH SALES AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES
      FROM BOOK_SALES
     WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
     GROUP BY BOOK_ID
)
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, 
       SUM(B.PRICE * S.SALES) AS TOTAL_SALES
  FROM SALES AS S
  LEFT JOIN BOOK AS B
    ON S.BOOK_ID = B.BOOK_ID
  LEFT JOIN AUTHOR AS A
    ON B.AUTHOR_ID = A.AUTHOR_ID
 GROUP BY AUTHOR_ID, CATEGORY
 ORDER BY AUTHOR_ID ASC, CATEGORY DESC;