-- 코드를 작성해주세요
WITH SECOND AS (
    SELECT A.ID AS PARENT_ID, B.ID
      FROM ECOLI_DATA AS A
      JOIN ECOLI_DATA AS B
        ON A.ID = B.PARENT_ID
     WHERE A.PARENT_ID IS NULL
)
SELECT DISTINCT D.ID
  FROM SECOND AS C
  JOIN ECOLI_DATA AS D
    ON C.ID = D.PARENT_ID
 ORDER BY ID ASC;