-- 코드를 작성해주세요
WITH CHILD AS (
    SELECT PARENT_ID, COUNT(*) AS COUNT
      FROM ECOLI_DATA
     GROUP BY PARENT_ID
)
SELECT A.ID, IFNULL(B.COUNT, 0) AS CHILD_COUNT
  FROM ECOLI_DATA AS A
  LEFT JOIN CHILD AS B
    ON A.ID = B.PARENT_ID
 ORDER BY ID;