-- 코드를 입력하세요
WITH FIRST_SALE AS (
    SELECT USER_ID, PRODUCT_ID, MIN(SALES_DATE) AS DATE
      FROM ONLINE_SALE
     GROUP BY USER_ID, PRODUCT_ID  
)
SELECT DISTINCT O.USER_ID, O.PRODUCT_ID
  FROM ONLINE_SALE AS O
  LEFT JOIN FIRST_SALE AS F
    ON O.USER_ID    = F.USER_ID
   AND O.PRODUCT_ID = F.PRODUCT_ID
   AND O.SALES_DATE = F.DATE
 WHERE F.DATE IS NULL
 ORDER BY USER_ID ASC, PRODUCT_ID DESC;