-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE,
       (C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100 * 30) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR AS C
  LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
    ON C.CAR_TYPE = D.CAR_TYPE
   AND D.DURATION_TYPE = '30일 이상'
 WHERE C.CAR_TYPE IN ('세단', 'SUV')
   AND (C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100 * 30) >= 500000 
   AND (C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100 * 30) < 2000000
   AND C.CAR_ID NOT IN (SELECT CAR_ID
                          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                         WHERE NOT (END_DATE < '2022-11-01' 
                                    OR START_DATE > '2022-11-30'))
 ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;