-- 코드를 입력하세요
SELECT R.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, 
       ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
  FROM REST_REVIEW AS R
  LEFT JOIN REST_INFO AS I
    ON R.REST_ID = I.REST_ID
 WHERE I.ADDRESS LIKE '서울%'
 GROUP BY REST_ID
 ORDER BY SCORE DESC, FAVORITES DESC;