-- 코드를 입력하세요
WITH TOTAL AS (
    SELECT COUNT(*) AS CNT
      FROM USER_INFO
     WHERE YEAR(JOINED) = 2021
)
SELECT YEAR(S.SALES_DATE) AS YEAR,
       MONTH(S.SALES_DATE) AS MONTH,
       COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT S.USER_ID) / (SELECT CNT FROM TOTAL), 1) AS PUCHASED_RATIO
  FROM ONLINE_SALE AS S
  LEFT JOIN USER_INFO AS U
    ON S.USER_ID = U.USER_ID
 WHERE YEAR(U.JOINED) = 2021
 GROUP BY YEAR, MONTH
 ORDER BY YEAR ASC, MONTH ASC;
