-- 코드를 작성해주세요
WITH RECURSIVE GEN_DATA AS (
    SELECT 1 AS GENERATION, ID, PARENT_ID
      FROM ECOLI_DATA
     WHERE PARENT_ID IS NULL
     
     UNION ALL 
    
    SELECT GENERATION+1 AS GENERATION, B.ID, B.PARENT_ID
      FROM GEN_DATA AS A
      JOIN ECOLI_DATA AS B
        ON B.PARENT_ID = A.ID
)
SELECT COUNT(*) AS COUNT, GENERATION
  FROM GEN_DATA AS A
 WHERE ID NOT IN (SELECT PARENT_ID
                    FROM GEN_DATA
                   WHERE GENERATION = A.GENERATION + 1)
 GROUP BY GENERATION 
 ORDER BY GENERATION ASC;