-- 코드를 입력하세요
WITH AVL AS (
    SELECT CAR_ID, START_DATE
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
)
SELECT DISTINCT H.CAR_ID,
       CASE WHEN A.START_DATE IS NOT NULL
                THEN '대여중'
                ELSE '대여 가능' END AS AVAILABILITY
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
  LEFT JOIN AVL AS A
    ON H.CAR_ID = A.CAR_ID
 ORDER BY CAR_ID DESC;