-- 코드를 입력하세요
WITH HISTORY AS (
    SELECT H.HISTORY_ID, C.CAR_TYPE, C.DAILY_FEE,
           DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DAYS,
           CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상' END AS DURATION_TYPE
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
      JOIN CAR_RENTAL_COMPANY_CAR AS C
        ON H.CAR_ID = C.CAR_ID
     WHERE C.CAR_TYPE = '트럭'
)
SELECT H.HISTORY_ID, 
       ROUND((H.DAILY_FEE * (100 - IFNULL(D.DISCOUNT_RATE, 0))/100 * H.DAYS), 0) AS FEE
  FROM HISTORY AS H
  LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
    ON H.DURATION_TYPE = D.DURATION_TYPE
   AND H.CAR_TYPE      = D.CAR_TYPE
 ORDER BY FEE DESC, HISTORY_ID DESC;
 