-- 코드를 입력하세요
WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR
     UNION ALL
    SELECT HOUR+1
      FROM TIME_TABLE
     WHERE HOUR < 23
)
SELECT A.HOUR, IFNULL(COUNT(ANIMAL_ID), 0) AS COUNT
  FROM TIME_TABLE AS A
  LEFT JOIN ANIMAL_OUTS AS B
    ON A.HOUR = HOUR(B.DATETIME)
 GROUP BY A.HOUR
 ORDER BY A.HOUR;