-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
  FROM USED_GOODS_BOARD AS B
  LEFT JOIN USED_GOODS_USER AS U
    ON B.WRITER_ID = U.USER_ID
 GROUP BY B.WRITER_ID, B.STATUS
HAVING TOTAL_SALES >= 700000
   AND STATUS = 'DONE'
 ORDER BY TOTAL_SALES ASC;