-- 코드를 입력하세요
SELECT P.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
  FROM REST_REVIEW AS R
  LEFT JOIN MEMBER_PROFILE AS P
    ON R.MEMBER_ID = P.MEMBER_ID
 WHERE P.MEMBER_ID = (SELECT MEMBER_ID
                        FROM REST_REVIEW
                       GROUP BY MEMBER_ID
                       ORDER BY COUNT(*) DESC
                       LIMIT 1)
 ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;