-- 코드를 작성해주세요
WITH MAX_COLONY AS (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE,
           YEAR(DIFFERENTIATION_DATE) AS YEAR
      FROM ECOLI_DATA
     GROUP BY YEAR
)

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
       (SELECT MAX_SIZE 
          FROM MAX_COLONY 
         WHERE YEAR = YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV,
       ID
  FROM ECOLI_DATA
 ORDER BY YEAR ASC, YEAR_DEV ASC;