-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS SCORE,
       E.EMP_NO,
       E.EMP_NAME,
       E.POSITION,
       E.EMAIL
  FROM HR_GRADE AS G
  LEFT JOIN HR_EMPLOYEES AS E
    ON G.EMP_NO = E.EMP_NO
 GROUP BY G.EMP_NO, G.YEAR
HAVING G.YEAR = 2022
 ORDER BY SCORE DESC
 LIMIT 1;